/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package DostawcaWarstwa_klienta;

import Warstwa_biznesowa.Fasada;
import Warstwa_biznesowa.Zamowienie;
import DostawcaWarstwa_integracji.TBase;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Graphics;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author Grzesiek
 */
public class Client extends javax.swing.JFrame {

    Fasada fasada = new Fasada();
    DostawcaTableModel model1;
    ProduktyzamowienieTableModel model3;
    TBase tbase = new TBase(fasada);
    String numerzamowienia = "";

    int row;

    public Client() {
        super();
        initComponents();
        CardLayout la = (CardLayout) this.getContentPane().getLayout();
        model1 = new DostawcaTableModel();

        Dostawcy.setPreferredScrollableViewportSize(new Dimension(500, 100));
        Dostawcy.setFillsViewportHeight(true);
        Dostawcy.getSelectionModel().addListSelectionListener(new RowListener1());
        Pozycje.setPreferredScrollableViewportSize(new Dimension(500, 100));
        Pozycje.setFillsViewportHeight(true);
        Pozycje.getSelectionModel().addListSelectionListener(new RowListener1());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pusty = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        Dodaj_dostawce = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Nazwa = new javax.swing.JTextField();
        NIP = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Adres1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Adres2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Nrtelefon = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Utwórzklienta = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Nrkonta = new javax.swing.JTextField();
        Dodaj_produkt = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Nazwa_prod = new javax.swing.JTextField();
        Producent = new javax.swing.JTextField();
        Kategoria = new javax.swing.JTextField();
        Cena = new javax.swing.JTextField();
        Dostawca = new javax.swing.JTextField();
        Add_produkt = new javax.swing.JButton();
        Dodaj_egzemplarz = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Produkty = new javax.swing.JTable();
        Dodaj_egz = new javax.swing.JButton();
        Numer_seryjny = new javax.swing.JTextField();
        Data_waznosci_D = new javax.swing.JTextField();
        Data_produkcji_D = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Egzemplarze = new javax.swing.JComboBox();
        Data_produkcji_M = new javax.swing.JTextField();
        Data_produkcji_Y = new javax.swing.JTextField();
        Data_waznosci_M = new javax.swing.JTextField();
        Data_waznosci_Y = new javax.swing.JTextField();
        Dodaj_zamowienie = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Dostawcy = new javax.swing.JTable();
        Lista_produktow = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        Ilosc = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        numerzam = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        Pozycje = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jButton1.setText("Dostawcy");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Produkty");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Zamówienia");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton7.setText("jButton7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PustyLayout = new javax.swing.GroupLayout(Pusty);
        Pusty.setLayout(PustyLayout);
        PustyLayout.setHorizontalGroup(
            PustyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PustyLayout.createSequentialGroup()
                .addGroup(PustyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PustyLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3))
                    .addGroup(PustyLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jButton7)))
                .addContainerGap(411, Short.MAX_VALUE))
        );
        PustyLayout.setVerticalGroup(
            PustyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PustyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PustyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(147, 147, 147)
                .addComponent(jButton7)
                .addContainerGap(391, Short.MAX_VALUE))
        );

        getContentPane().add(Pusty, "card3");

        jLabel1.setText("Nazwa:");

        Nazwa.setName("Nazwa"); // NOI18N

        NIP.setName("NIP"); // NOI18N

        jLabel2.setText("NIP:");

        Adres1.setName("Adres1"); // NOI18N

        jLabel3.setText("Adres: ");
        jLabel3.setName("Adres1"); // NOI18N

        Adres2.setName("Adres2"); // NOI18N

        jLabel4.setText("Kod pocztowy: ");
        jLabel4.setName("Adres2"); // NOI18N

        Nrtelefon.setName("Nrtelefon"); // NOI18N

        jLabel5.setText("Nr telefonu: ");
        jLabel5.setName("Nrtelefon"); // NOI18N

        Utwórzklienta.setText("Utwórz dostawcę");
        Utwórzklienta.setName("Utwórz klienta"); // NOI18N
        Utwórzklienta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UtwórzklientaActionPerformed(evt);
            }
        });

        jLabel6.setText("Numer konta: ");
        jLabel6.setName("Login"); // NOI18N

        Nrkonta.setName("Nrkonta"); // NOI18N

        javax.swing.GroupLayout Dodaj_dostawceLayout = new javax.swing.GroupLayout(Dodaj_dostawce);
        Dodaj_dostawce.setLayout(Dodaj_dostawceLayout);
        Dodaj_dostawceLayout.setHorizontalGroup(
            Dodaj_dostawceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dodaj_dostawceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Dodaj_dostawceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Dodaj_dostawceLayout.createSequentialGroup()
                        .addGroup(Dodaj_dostawceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Dodaj_dostawceLayout.createSequentialGroup()
                                .addGroup(Dodaj_dostawceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(Dodaj_dostawceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Nazwa)
                                    .addComponent(NIP)
                                    .addComponent(Adres1)
                                    .addComponent(Adres2)))
                            .addGroup(Dodaj_dostawceLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(30, 30, 30)
                                .addGroup(Dodaj_dostawceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Dodaj_dostawceLayout.createSequentialGroup()
                                        .addComponent(Utwórzklienta)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(Nrtelefon, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                                    .addComponent(Nrkonta))))
                        .addGap(199, 199, 199))
                    .addGroup(Dodaj_dostawceLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        Dodaj_dostawceLayout.setVerticalGroup(
            Dodaj_dostawceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dodaj_dostawceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Dodaj_dostawceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(Nazwa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Dodaj_dostawceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Dodaj_dostawceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Adres1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Dodaj_dostawceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Adres2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Dodaj_dostawceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Nrtelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Dodaj_dostawceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Nrkonta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 366, Short.MAX_VALUE)
                .addComponent(Utwórzklienta)
                .addGap(30, 30, 30))
        );

        jLabel1.getAccessibleContext().setAccessibleName("Imie");
        jLabel1.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(Dodaj_dostawce, "Dostawcy");

        jLabel7.setText("Nazwa");

        jLabel8.setText("Producent");

        jLabel9.setText("Kategoria");

        jLabel10.setText("Cena");

        jLabel11.setText("Dostawca");

        Nazwa_prod.setName("Nazwa"); // NOI18N

        Producent.setName("Producent"); // NOI18N
        Producent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProducentActionPerformed(evt);
            }
        });

        Kategoria.setName("Kategoria"); // NOI18N
        Kategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KategoriaActionPerformed(evt);
            }
        });

        Cena.setName("Cena"); // NOI18N
        Cena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CenaActionPerformed(evt);
            }
        });

        Dostawca.setName("Dostawca"); // NOI18N
        Dostawca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DostawcaActionPerformed(evt);
            }
        });

        Add_produkt.setText("Dodaj produkt");
        Add_produkt.setName("Dodaj_produkt"); // NOI18N
        Add_produkt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_produktActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Dodaj_produktLayout = new javax.swing.GroupLayout(Dodaj_produkt);
        Dodaj_produkt.setLayout(Dodaj_produktLayout);
        Dodaj_produktLayout.setHorizontalGroup(
            Dodaj_produktLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dodaj_produktLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Dodaj_produktLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Dodaj_produktLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Kategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Dodaj_produktLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Cena, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Dodaj_produktLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Producent, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Dodaj_produktLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(41, 41, 41)
                        .addComponent(Nazwa_prod, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Dodaj_produktLayout.createSequentialGroup()
                        .addGroup(Dodaj_produktLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Add_produkt)
                            .addGroup(Dodaj_produktLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Dostawca, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(1, 1, 1)))
                .addContainerGap(517, Short.MAX_VALUE))
        );
        Dodaj_produktLayout.setVerticalGroup(
            Dodaj_produktLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dodaj_produktLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Dodaj_produktLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Nazwa_prod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(Dodaj_produktLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Producent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(Dodaj_produktLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Dodaj_produktLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel9))
                    .addGroup(Dodaj_produktLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Kategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Dodaj_produktLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(Cena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Dodaj_produktLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(Dostawca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(Add_produkt)
                .addContainerGap(327, Short.MAX_VALUE))
        );

        Add_produkt.getAccessibleContext().setAccessibleName("");

        getContentPane().add(Dodaj_produkt, "Produkty");

        Produkty.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Produkty);

        Dodaj_egz.setText("Dodaj egzemplarz");
        Dodaj_egz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dodaj_egzActionPerformed(evt);
            }
        });

        jLabel12.setText("Numer seryjny: ");

        jLabel13.setText("Data produkcji: ");

        jLabel14.setText("Data ważności: ");

        Egzemplarze.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout Dodaj_egzemplarzLayout = new javax.swing.GroupLayout(Dodaj_egzemplarz);
        Dodaj_egzemplarz.setLayout(Dodaj_egzemplarzLayout);
        Dodaj_egzemplarzLayout.setHorizontalGroup(
            Dodaj_egzemplarzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dodaj_egzemplarzLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Dodaj_egzemplarzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Dodaj_egzemplarzLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Dodaj_egz)
                        .addGap(71, 71, 71))
                    .addGroup(Dodaj_egzemplarzLayout.createSequentialGroup()
                        .addGroup(Dodaj_egzemplarzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Dodaj_egzemplarzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(Dodaj_egzemplarzLayout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addGroup(Dodaj_egzemplarzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel14)
                                        .addComponent(Egzemplarze, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(Dodaj_egzemplarzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(Dodaj_egzemplarzLayout.createSequentialGroup()
                                            .addComponent(Data_waznosci_D, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(Data_waznosci_M, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(Data_waznosci_Y, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(Dodaj_egzemplarzLayout.createSequentialGroup()
                                            .addComponent(Data_produkcji_D, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(Data_produkcji_M, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(Data_produkcji_Y, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Dodaj_egzemplarzLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(Numer_seryjny, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(351, Short.MAX_VALUE))))
        );
        Dodaj_egzemplarzLayout.setVerticalGroup(
            Dodaj_egzemplarzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dodaj_egzemplarzLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 348, Short.MAX_VALUE)
                .addGroup(Dodaj_egzemplarzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Numer_seryjny, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Dodaj_egzemplarzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Data_produkcji_D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(Data_produkcji_M, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Data_produkcji_Y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(Dodaj_egzemplarzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Dodaj_egz)
                    .addComponent(Data_waznosci_D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(Data_waznosci_M, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Data_waznosci_Y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Egzemplarze, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        getContentPane().add(Dodaj_egzemplarz, "Egzemplarze");

        jLabel15.setText("Dostawcy");

        jLabel17.setText("Produkty");

        jButton5.setText("Dodaj produkt do zamówienia");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        Dostawcy.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(Dostawcy);

        Lista_produktow.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel16.setText("Ilość");

        jButton4.setText("Zakoncz zamowienie");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel18.setText("Numer zamówienia");

        jButton6.setText("Dodaj zamówienie");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        numerzam.setName("nr"); // NOI18N

        Pozycje.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(Pozycje);

        javax.swing.GroupLayout Dodaj_zamowienieLayout = new javax.swing.GroupLayout(Dodaj_zamowienie);
        Dodaj_zamowienie.setLayout(Dodaj_zamowienieLayout);
        Dodaj_zamowienieLayout.setHorizontalGroup(
            Dodaj_zamowienieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dodaj_zamowienieLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Dodaj_zamowienieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Dodaj_zamowienieLayout.createSequentialGroup()
                        .addGroup(Dodaj_zamowienieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Dodaj_zamowienieLayout.createSequentialGroup()
                                .addGroup(Dodaj_zamowienieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Dodaj_zamowienieLayout.createSequentialGroup()
                                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                                        .addGap(96, 96, 96))
                                    .addGroup(Dodaj_zamowienieLayout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(72, 72, 72)))
                                .addGroup(Dodaj_zamowienieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(numerzam))
                                .addGap(226, 226, 226))
                            .addGroup(Dodaj_zamowienieLayout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(Dodaj_zamowienieLayout.createSequentialGroup()
                        .addGroup(Dodaj_zamowienieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lista_produktow, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Dodaj_zamowienieLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(217, 217, 217)
                                .addGroup(Dodaj_zamowienieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Ilosc, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButton6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))))
        );
        Dodaj_zamowienieLayout.setVerticalGroup(
            Dodaj_zamowienieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dodaj_zamowienieLayout.createSequentialGroup()
                .addGroup(Dodaj_zamowienieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Dodaj_zamowienieLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(Dodaj_zamowienieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Dodaj_zamowienieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numerzam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Dodaj_zamowienieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Dodaj_zamowienieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lista_produktow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ilosc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(Dodaj_zamowienieLayout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jButton4)
                .addContainerGap(246, Short.MAX_VALUE))
        );

        getContentPane().add(Dodaj_zamowienie, "Zamowienia");

        jMenu1.setText("File");

        jMenuItem3.setText("Zamówienia");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void list_content(ArrayList<String> col,
            JComboBox list) {
        String s;
        list.removeAllItems();
        Iterator<String> iterator = col.iterator();
        while (iterator.hasNext()) {
            s = iterator.next();
            list.addItem(s);
        }
    }

    public void paintComponent(Graphics g) {
        paintComponent(g);
    }

    void table_content2(String numerzamowienia) {
        // Produkty_zamowienie.setModel(model1);
        tbase.update_data();

        model3 = new ProduktyzamowienieTableModel();
        Pozycje.setModel(model3);
        tbase.update_data();
        Object[][] produkty = fasada.getpozycje(numerzamowienia);

        model3.setData(produkty);
    }

    class MyTableModel extends AbstractTableModel {

        private String[] columnNames = {"Nazwa",
            "Producent",
            "Kategoria"
        };
        private Object[][] data;

        public void setData(Object[][] val) {
            data = val;
        }

        public int getColumnCount() {
            return columnNames.length;
        }

        public int getRowCount() {
            return data.length;
        }

        public String getColumnName(int col) {
            return columnNames[col];
        }

        public Object getValueAt(int row, int col) {
            return data[row][col];
        }

        public Class getColumnClass(int c) {
            return getValueAt(0, c).getClass();
        }

        public boolean isCellEditable(int row, int col) {
            if (col < 0) {
                return false;
            } else {
                return true;
            }
        }

        public void setValueAt(Object value, int row, int col) {
            data[row][col] = value;
            fireTableCellUpdated(row, col);
        }
    }

    class DostawcaTableModel extends MyTableModel {

        private String[] columnNames1 = {
            "Nazwa",
            "Adres",
            "NIP"
        };

        public String getColumnName(int col) {
            return columnNames1[col];
        }
    }

    class ProduktyzamowienieTableModel extends DostawcaTableModel {

        private String[] columnNames2 = {
            "Nazwa",
            "Producent",
            "Ilość"
        };

        public String getColumnName(int col) {
            return columnNames2[col];
        }
    }

    private class RowListener1 implements ListSelectionListener {

        public void valueChanged(ListSelectionEvent event) {
            if (event.getValueIsAdjusting()) {
                return;
            }

        }
    }

    private void UtwórzklientaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UtwórzklientaActionPerformed

        String dane_dostawca1[] = {Nazwa.getText(), NIP.getText(), Adres1.getText(), Adres2.getText(), Nrtelefon.getText(), Nrkonta.getText()};

        if (dane_dostawca1[0].equals("") || dane_dostawca1[1].equals("") || dane_dostawca1[2].equals("") || dane_dostawca1[3].equals("") || dane_dostawca1[4].equals("") || dane_dostawca1[5].equals("")) {
            JOptionPane.showMessageDialog(this, "Prosze podać dane");
            return;
        }

        try {
            Integer.parseInt(Nrtelefon.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "W polu 'numer telefonu' wymagany format liczbowy");
            return;
        }

        String wynik = fasada.dodaj_klienta(dane_dostawca1);
        if (wynik == null) {
            JOptionPane.showMessageDialog(this, "Ten dostawca już istnieje");
        } else {
            JOptionPane.showMessageDialog(this, "Utworzono dostawce o numerze NIP " + NIP.getText().toString());
        }

        Nazwa.setText("");
        NIP.setText("");
        Adres1.setText("");
        Adres2.setText("");
        Nrtelefon.setText("");
        Nrkonta.setText("");

  // table_content1();  
        // TODO add your handling code here:
    }//GEN-LAST:event_UtwórzklientaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CardLayout la = (CardLayout) this.getContentPane().getLayout();
        la.show(this.getContentPane(), "Dostawcy");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CardLayout la = (CardLayout) this.getContentPane().getLayout();
        la.show(this.getContentPane(), "Produkty");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ProducentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProducentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProducentActionPerformed

    private void KategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KategoriaActionPerformed

    private void CenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CenaActionPerformed

    private void DostawcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DostawcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DostawcaActionPerformed

    private void Add_produktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_produktActionPerformed
        String k;
        String data[] = {Nazwa_prod.getText(), Producent.getText(), Kategoria.getText(), Cena.getText(), Dostawca.getText()};
        if (Nazwa_prod.getText().equals("") || Producent.getText().equals("") || Kategoria.getText().equals("") || Cena.getText().equals("") || Dostawca.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Prosze podać dane");
            return;
        }
        try {
            Float.parseFloat(Cena.getText());

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "W polu 'cena' wymagany format liczbowy");
            return;
        }
        try {
            Integer.parseInt(Dostawca.getText());

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "W polu 'Dostawca' wymagany format liczbowy");
            return;
        }

// k= fasada.dodaj_produkt(data);
        //if (k=="brak")
        {
            JOptionPane.showMessageDialog(null, "Dostawca produktu nie istnieje w bazie");
        }

        //if (k==null)
        {
            JOptionPane.showMessageDialog(null, "Produkt o podanych parametrach już istnieje w bazie");
        }
        //if (k=="OK")
        {
            JOptionPane.showMessageDialog(null, "Dodano produkt do bazy");
        }

        Nazwa_prod.setText("");
        Producent.setText("");
        Kategoria.setText("");
        Cena.setText("");
        Dostawca.setText("");
       // table_content();

        // TODO add your handling code here:
    }//GEN-LAST:event_Add_produktActionPerformed

    private void Dodaj_egzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dodaj_egzActionPerformed

        if (!Produkty.getSelectionModel().isSelectionEmpty()) {

            if (Numer_seryjny.getText().equals("") || Data_waznosci_D.getText().equals("") || Data_produkcji_D.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Prosze podać dane");
                return;
            }
            try {
                Integer.parseInt(Numer_seryjny.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Wymagany format liczbowy");
                return;
            }

            /*      
             String nazwa =(String) model.getValueAt(row, 0);
             String producent = (String) model.getValueAt(row, 1);
             String data2[] = {nazwa,producent,Numer_seryjny.getText(),Data_produkcji_D.getText(),Data_produkcji_M.getText(),Data_produkcji_Y.getText(),Data_waznosci_D.getText(),Data_waznosci_M.getText(),Data_waznosci_Y.getText()};
             String dane_1 [] = {(String) model.getValueAt(row, 0),(String) model.getValueAt(row, 1)};
             */
       //    fasada.dodaj_egzemplarzproduktu(data2);
            //tbase.update_data();
       //     ArrayList<String> help3 = fasada.getegzemplarze(dane_1);
        //    if (help3 != null) {
            //      list_content(help3, Egzemplarze);
            //   }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_Dodaj_egzActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        CardLayout la = (CardLayout) this.getContentPane().getLayout();
        la.show(this.getContentPane(), "Zamowienia");

      //  Pokaz_produkty();
      //     ArrayList<String> help3 =  fasada.getdostawcy2();
        //   if (help3 != null) {
        //         list_content(help3, Dostawcy);
        //   }
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        tbase.update_data();

        String nr_zam1 = numerzam.getText().toString();
        String ilosc = Ilosc.getText().toString();
        String dost1 = model1.getValueAt(row, 2).toString();
        int wybranyprodukt = Lista_produktow.getSelectedIndex();

 //fasada.dodaj_pozycje_zamowienia(wybranyprodukt, dost1, nr_zam1, ilosc);
        tbase.dodaj_pozycje_zamowien();
        table_content2(nr_zam1);

// 
   //     Object[][] produkty = fasada.getproduktydozamowienia(dane1,wybrany,ilosc);
        //   model2 = new ProduktyzamowienieTableModel(); 
        //model2.setData(produkty);   
        //   Produkty_zamowienie.setModel(model2);
        //Pozycje.setVisible(false);
        // table_content1();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String nr_zam1 = numerzam.getText().toString();
        String danedostawcy = model1.getValueAt(row, 2).toString();

        fasada.dodaj_zamowienie1(danedostawcy, nr_zam1);
        tbase.dodaj_zamowienia();
        System.out.println(fasada.getZamowienia().toString());
        table_content2(nr_zam1);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        Zamowienie zamowienie = new Zamowienie();
        Zamowienie zamówienie = new Zamowienie();
        zamowienie.setNr_zamówienia("1");
        zamówienie = fasada.Szukajzamowienie(zamowienie);
        //fasada.Szukajzamowienietest(nrzamowienia);
        String numer = zamówienie.getNr_zamówienia().toString();
        System.out.println(numer);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Client().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_produkt;
    private javax.swing.JTextField Adres1;
    private javax.swing.JTextField Adres2;
    private javax.swing.JTextField Cena;
    private javax.swing.JTextField Data_produkcji_D;
    private javax.swing.JTextField Data_produkcji_M;
    private javax.swing.JTextField Data_produkcji_Y;
    private javax.swing.JTextField Data_waznosci_D;
    private javax.swing.JTextField Data_waznosci_M;
    private javax.swing.JTextField Data_waznosci_Y;
    private javax.swing.JPanel Dodaj_dostawce;
    private javax.swing.JButton Dodaj_egz;
    private javax.swing.JPanel Dodaj_egzemplarz;
    private javax.swing.JPanel Dodaj_produkt;
    private javax.swing.JPanel Dodaj_zamowienie;
    private javax.swing.JTextField Dostawca;
    private javax.swing.JTable Dostawcy;
    private javax.swing.JComboBox Egzemplarze;
    private javax.swing.JTextField Ilosc;
    private javax.swing.JTextField Kategoria;
    private javax.swing.JComboBox Lista_produktow;
    private javax.swing.JTextField NIP;
    private javax.swing.JTextField Nazwa;
    private javax.swing.JTextField Nazwa_prod;
    private javax.swing.JTextField Nrkonta;
    private javax.swing.JTextField Nrtelefon;
    private javax.swing.JTextField Numer_seryjny;
    private javax.swing.JTable Pozycje;
    private javax.swing.JTextField Producent;
    private javax.swing.JTable Produkty;
    private javax.swing.JPanel Pusty;
    private javax.swing.JButton Utwórzklienta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField numerzam;
    // End of variables declaration//GEN-END:variables
}
