/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sklep_v1_client_ejb;

import business_tier.FacadeRemote;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Graphics;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.annotation.Resource;
import javax.ejb.EJB;
import javax.jms.Connection;
import javax.jms.ConnectionFactory;
import javax.jms.Destination;
import javax.jms.JMSException;
import javax.jms.Message;
import javax.jms.MessageConsumer;
import javax.jms.ObjectMessage;
import javax.jms.Queue;
import javax.jms.Session;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.AbstractTableModel;
import message.messagebeanRemote;
import wyniki.Zapis_wynikow;

/**
 *
 * @author Grzesiek
 */
public class Client_Sklep extends javax.swing.JFrame {

    @EJB
    private static FacadeRemote fasada;
    @EJB
    private static messagebeanRemote messagebean;

    @Resource(mappedName = "jms/JupiterConnectionFactory")
    private static ConnectionFactory connectionFactory = null;

    @Resource(mappedName = "jms/Queue")
    private static Queue queue = null;
    @Resource(mappedName = "jms/Reply")
    private static Queue reply = null;
    // 
int licznik = 0;
    DostawcaTableModel model1;
    ProduktyzamowienieTableModel model3;

    int row;

    public Client_Sklep() {
        super();
        initComponents();
        CardLayout la = (CardLayout) this.getContentPane().getLayout();
        model1 = new DostawcaTableModel();

        table_content1();
        Dostawcy.setPreferredScrollableViewportSize(new Dimension(500, 100));
        Dostawcy.setFillsViewportHeight(true);
        Dostawcy.getSelectionModel().addListSelectionListener(new RowListener1());
        Pozycje.setPreferredScrollableViewportSize(new Dimension(500, 100));
        Pozycje.setFillsViewportHeight(true);
        Pozycje.getSelectionModel().addListSelectionListener(new RowListener1());
        Dostawcy1.setPreferredScrollableViewportSize(new Dimension(500, 100));
        Dostawcy1.setFillsViewportHeight(true);
        Dostawcy1.getSelectionModel().addListSelectionListener(new RowListener2());

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pusty = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        Dodaj_dostawce = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Nazwa = new javax.swing.JTextField();
        NIP = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Adres1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Adres2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Nrtelefon = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Utworzdostawce = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Nrkonta = new javax.swing.JTextField();
        Dodaj_produkt = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Nazwa_prod = new javax.swing.JTextField();
        Producent = new javax.swing.JTextField();
        Kategoria = new javax.swing.JTextField();
        Cena = new javax.swing.JTextField();
        Dostawca = new javax.swing.JTextField();
        Add_produkt = new javax.swing.JButton();
        ilosc = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        Dodaj_egzemplarz = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Produkty = new javax.swing.JTable();
        Dodaj_egz = new javax.swing.JButton();
        Numer_seryjny = new javax.swing.JTextField();
        Data_waznosci_D = new javax.swing.JTextField();
        Data_produkcji_D = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Egzemplarze = new javax.swing.JComboBox();
        Data_produkcji_M = new javax.swing.JTextField();
        Data_produkcji_Y = new javax.swing.JTextField();
        Data_waznosci_M = new javax.swing.JTextField();
        Data_waznosci_Y = new javax.swing.JTextField();
        Dodaj_zamowienie = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Dostawcy = new javax.swing.JTable();
        Lista_produktow = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        Ilosc = new javax.swing.JTextField();
        Wyslij_zamowienie = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        numerzam = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        Pozycje = new javax.swing.JTable();
        jButton8 = new javax.swing.JButton();
        Zapytanieoprodukt = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Dostawcy1 = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        produktydostawcy1 = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        tresc_zapytania = new javax.swing.JTextField();
        Wyślij_zapytanie = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        Dodajklienta = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        Imie = new javax.swing.JTextField();
        Nazwisko = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        KAdres1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        KAdres2 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        KNrtelefon = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        Utwórzklienta = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        Pesel = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        Dodaj_klienta = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikacja Sklep");
        getContentPane().setLayout(new java.awt.CardLayout());

        jButton1.setText("Dostawcy");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Produkty");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Zamówienia");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("test");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton7.setText("czas");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PustyLayout = new javax.swing.GroupLayout(Pusty);
        Pusty.setLayout(PustyLayout);
        PustyLayout.setHorizontalGroup(
            PustyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PustyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PustyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PustyLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3))
                    .addGroup(PustyLayout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(74, 74, 74)
                        .addComponent(jButton7)))
                .addContainerGap(401, Short.MAX_VALUE))
        );
        PustyLayout.setVerticalGroup(
            PustyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PustyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PustyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(124, 124, 124)
                .addGroup(PustyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton7))
                .addContainerGap(429, Short.MAX_VALUE))
        );

        getContentPane().add(Pusty, "Pusty");

        jLabel1.setText("Nazwa:");

        Nazwa.setName("Nazwa"); // NOI18N

        NIP.setName("NIP"); // NOI18N

        jLabel2.setText("NIP:");

        Adres1.setName("Adres1"); // NOI18N

        jLabel3.setText("Adres: ");
        jLabel3.setName("Adres1"); // NOI18N

        Adres2.setName("Adres2"); // NOI18N

        jLabel4.setText("Kod pocztowy: ");
        jLabel4.setName("Adres2"); // NOI18N

        Nrtelefon.setName("Nrtelefon"); // NOI18N

        jLabel5.setText("Nr telefonu: ");
        jLabel5.setName("Nrtelefon"); // NOI18N

        Utworzdostawce.setText("Utwórz dostawcę");
        Utworzdostawce.setName("Utwórz klienta"); // NOI18N
        Utworzdostawce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UtworzdostawceActionPerformed(evt);
            }
        });

        jLabel6.setText("Numer konta: ");
        jLabel6.setName("Login"); // NOI18N

        Nrkonta.setName("Nrkonta"); // NOI18N

        javax.swing.GroupLayout Dodaj_dostawceLayout = new javax.swing.GroupLayout(Dodaj_dostawce);
        Dodaj_dostawce.setLayout(Dodaj_dostawceLayout);
        Dodaj_dostawceLayout.setHorizontalGroup(
            Dodaj_dostawceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dodaj_dostawceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Dodaj_dostawceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Dodaj_dostawceLayout.createSequentialGroup()
                        .addGroup(Dodaj_dostawceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Dodaj_dostawceLayout.createSequentialGroup()
                                .addGroup(Dodaj_dostawceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(Dodaj_dostawceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Nazwa)
                                    .addComponent(NIP)
                                    .addComponent(Adres1)
                                    .addComponent(Adres2)))
                            .addGroup(Dodaj_dostawceLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(30, 30, 30)
                                .addGroup(Dodaj_dostawceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Dodaj_dostawceLayout.createSequentialGroup()
                                        .addComponent(Utworzdostawce)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(Nrtelefon, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                                    .addComponent(Nrkonta))))
                        .addGap(199, 199, 199))
                    .addGroup(Dodaj_dostawceLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        Dodaj_dostawceLayout.setVerticalGroup(
            Dodaj_dostawceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dodaj_dostawceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Dodaj_dostawceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(Nazwa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Dodaj_dostawceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Dodaj_dostawceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Adres1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Dodaj_dostawceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Adres2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Dodaj_dostawceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Nrtelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Dodaj_dostawceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Nrkonta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 381, Short.MAX_VALUE)
                .addComponent(Utworzdostawce)
                .addGap(30, 30, 30))
        );

        jLabel1.getAccessibleContext().setAccessibleName("Imie");
        jLabel1.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(Dodaj_dostawce, "Dostawcy");

        jLabel7.setText("Nazwa produktu: ");

        jLabel8.setText("Producent");

        jLabel9.setText("Kategoria");

        jLabel10.setText("Cena");

        jLabel11.setText("Dostawca produktu: ");

        Nazwa_prod.setName("Nazwa"); // NOI18N

        Producent.setName("Producent"); // NOI18N
        Producent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProducentActionPerformed(evt);
            }
        });

        Kategoria.setName("Kategoria"); // NOI18N
        Kategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KategoriaActionPerformed(evt);
            }
        });

        Cena.setName("Cena"); // NOI18N
        Cena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CenaActionPerformed(evt);
            }
        });

        Dostawca.setName("Dostawca"); // NOI18N
        Dostawca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DostawcaActionPerformed(evt);
            }
        });

        Add_produkt.setText("Dodaj produkt");
        Add_produkt.setName("Dodaj_produkt"); // NOI18N
        Add_produkt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_produktActionPerformed(evt);
            }
        });

        jLabel28.setText("Ilość: ");

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel29.setText("Dodawanie produktu do bazy danych");

        javax.swing.GroupLayout Dodaj_produktLayout = new javax.swing.GroupLayout(Dodaj_produkt);
        Dodaj_produkt.setLayout(Dodaj_produktLayout);
        Dodaj_produktLayout.setHorizontalGroup(
            Dodaj_produktLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dodaj_produktLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Dodaj_produktLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addGroup(Dodaj_produktLayout.createSequentialGroup()
                        .addGroup(Dodaj_produktLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel28))
                        .addGap(10, 10, 10)
                        .addGroup(Dodaj_produktLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Dostawca, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ilosc, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cena, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Kategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Producent, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nazwa_prod, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Add_produkt))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Dodaj_produktLayout.createSequentialGroup()
                .addContainerGap(239, Short.MAX_VALUE)
                .addComponent(jLabel29)
                .addGap(220, 220, 220))
        );
        Dodaj_produktLayout.setVerticalGroup(
            Dodaj_produktLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dodaj_produktLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29)
                .addGap(24, 24, 24)
                .addGroup(Dodaj_produktLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nazwa_prod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(15, 15, 15)
                .addGroup(Dodaj_produktLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Producent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(15, 15, 15)
                .addGroup(Dodaj_produktLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Kategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(15, 15, 15)
                .addGroup(Dodaj_produktLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(15, 15, 15)
                .addGroup(Dodaj_produktLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ilosc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addGap(15, 15, 15)
                .addGroup(Dodaj_produktLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Dostawca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(15, 15, 15)
                .addComponent(Add_produkt)
                .addContainerGap(325, Short.MAX_VALUE))
        );

        Add_produkt.getAccessibleContext().setAccessibleName("");

        getContentPane().add(Dodaj_produkt, "Produkty");

        Produkty.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Produkty);

        Dodaj_egz.setText("Dodaj egzemplarz");
        Dodaj_egz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dodaj_egzActionPerformed(evt);
            }
        });

        jLabel12.setText("Numer seryjny: ");

        jLabel13.setText("Data produkcji: ");

        jLabel14.setText("Data ważności: ");

        Egzemplarze.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout Dodaj_egzemplarzLayout = new javax.swing.GroupLayout(Dodaj_egzemplarz);
        Dodaj_egzemplarz.setLayout(Dodaj_egzemplarzLayout);
        Dodaj_egzemplarzLayout.setHorizontalGroup(
            Dodaj_egzemplarzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dodaj_egzemplarzLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Dodaj_egzemplarzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Dodaj_egzemplarzLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Dodaj_egz)
                        .addGap(71, 71, 71))
                    .addGroup(Dodaj_egzemplarzLayout.createSequentialGroup()
                        .addGroup(Dodaj_egzemplarzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Dodaj_egzemplarzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(Dodaj_egzemplarzLayout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addGroup(Dodaj_egzemplarzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel14)
                                        .addComponent(Egzemplarze, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(Dodaj_egzemplarzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(Dodaj_egzemplarzLayout.createSequentialGroup()
                                            .addComponent(Data_waznosci_D, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(Data_waznosci_M, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(Data_waznosci_Y, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(Dodaj_egzemplarzLayout.createSequentialGroup()
                                            .addComponent(Data_produkcji_D, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(Data_produkcji_M, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(Data_produkcji_Y, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Dodaj_egzemplarzLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(Numer_seryjny, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(341, Short.MAX_VALUE))))
        );
        Dodaj_egzemplarzLayout.setVerticalGroup(
            Dodaj_egzemplarzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dodaj_egzemplarzLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 363, Short.MAX_VALUE)
                .addGroup(Dodaj_egzemplarzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Numer_seryjny, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Dodaj_egzemplarzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Data_produkcji_D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(Data_produkcji_M, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Data_produkcji_Y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(Dodaj_egzemplarzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Dodaj_egz)
                    .addComponent(Data_waznosci_D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(Data_waznosci_M, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Data_waznosci_Y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Egzemplarze, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        getContentPane().add(Dodaj_egzemplarz, "Egzemplarze");

        jLabel15.setText("Dostawcy");

        jLabel17.setText("Produkty");

        jButton5.setText("Dodaj produkt do zamówienia");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        Dostawcy.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(Dostawcy);

        Lista_produktow.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel16.setText("Ilość");

        Wyslij_zamowienie.setText("Wyślij zamówienie");
        Wyslij_zamowienie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Wyslij_zamowienieActionPerformed(evt);
            }
        });

        jLabel18.setText("Numer zamówienia");

        jButton6.setText("Dodaj zamówienie");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        numerzam.setName("nr"); // NOI18N

        Pozycje.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(Pozycje);

        jButton8.setText("pozycje");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Dodaj_zamowienieLayout = new javax.swing.GroupLayout(Dodaj_zamowienie);
        Dodaj_zamowienie.setLayout(Dodaj_zamowienieLayout);
        Dodaj_zamowienieLayout.setHorizontalGroup(
            Dodaj_zamowienieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dodaj_zamowienieLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Dodaj_zamowienieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Dodaj_zamowienieLayout.createSequentialGroup()
                        .addGroup(Dodaj_zamowienieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Dodaj_zamowienieLayout.createSequentialGroup()
                                .addGroup(Dodaj_zamowienieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Dodaj_zamowienieLayout.createSequentialGroup()
                                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(96, 96, 96))
                                    .addGroup(Dodaj_zamowienieLayout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(72, 72, 72)))
                                .addGroup(Dodaj_zamowienieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(numerzam))
                                .addGap(226, 226, 226))
                            .addGroup(Dodaj_zamowienieLayout.createSequentialGroup()
                                .addComponent(Wyslij_zamowienie)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(Dodaj_zamowienieLayout.createSequentialGroup()
                        .addGroup(Dodaj_zamowienieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lista_produktow, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Dodaj_zamowienieLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(217, 217, 217)
                                .addGroup(Dodaj_zamowienieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Ilosc, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButton6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))))
            .addGroup(Dodaj_zamowienieLayout.createSequentialGroup()
                .addGap(279, 279, 279)
                .addComponent(jButton8)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Dodaj_zamowienieLayout.setVerticalGroup(
            Dodaj_zamowienieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dodaj_zamowienieLayout.createSequentialGroup()
                .addGroup(Dodaj_zamowienieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Dodaj_zamowienieLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(Dodaj_zamowienieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Dodaj_zamowienieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numerzam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Dodaj_zamowienieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Dodaj_zamowienieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lista_produktow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ilosc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(Dodaj_zamowienieLayout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(Wyslij_zamowienie)
                .addGap(40, 40, 40)
                .addComponent(jButton8)
                .addContainerGap(209, Short.MAX_VALUE))
        );

        getContentPane().add(Dodaj_zamowienie, "Zamowienia");

        Dostawcy1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Dostawcy1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane3.setViewportView(Dostawcy1);

        jLabel19.setText("Dostawcy");

        jLabel20.setText("Produkty dostawcy");

        produktydostawcy1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel21.setText("Treść zapytania ");

        Wyślij_zapytanie.setText("Wyślij");
        Wyślij_zapytanie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Wyślij_zapytanieActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel30.setText("Wysyłanie zapytania o produkt do dostawcy");

        javax.swing.GroupLayout ZapytanieoproduktLayout = new javax.swing.GroupLayout(Zapytanieoprodukt);
        Zapytanieoprodukt.setLayout(ZapytanieoproduktLayout);
        ZapytanieoproduktLayout.setHorizontalGroup(
            ZapytanieoproduktLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ZapytanieoproduktLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(ZapytanieoproduktLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(tresc_zapytania, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
            .addGroup(ZapytanieoproduktLayout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addGroup(ZapytanieoproduktLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(produktydostawcy1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addContainerGap(453, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ZapytanieoproduktLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ZapytanieoproduktLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ZapytanieoproduktLayout.createSequentialGroup()
                        .addComponent(Wyślij_zapytanie)
                        .addGap(222, 222, 222))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ZapytanieoproduktLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(232, 232, 232))))
        );
        ZapytanieoproduktLayout.setVerticalGroup(
            ZapytanieoproduktLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ZapytanieoproduktLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel30)
                .addGap(26, 26, 26)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(produktydostawcy1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel21)
                .addGap(22, 22, 22)
                .addComponent(tresc_zapytania, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Wyślij_zapytanie)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(Zapytanieoprodukt, "Zapytanie");

        jLabel22.setText("Imie:");

        Imie.setName("Nazwa"); // NOI18N

        Nazwisko.setName("NIP"); // NOI18N

        jLabel23.setText("Nazwisko:");

        KAdres1.setName("Adres1"); // NOI18N

        jLabel24.setText("Adres: ");
        jLabel24.setName("Adres1"); // NOI18N

        KAdres2.setName("Adres2"); // NOI18N

        jLabel25.setText("Kod pocztowy: ");
        jLabel25.setName("Adres2"); // NOI18N

        KNrtelefon.setName("Nrtelefon"); // NOI18N

        jLabel26.setText("Nr telefonu: ");
        jLabel26.setName("Nrtelefon"); // NOI18N

        Utwórzklienta.setText("Utwórz klienta");
        Utwórzklienta.setName("Utwórz klienta"); // NOI18N
        Utwórzklienta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UtwórzklientaActionPerformed(evt);
            }
        });

        jLabel27.setText("Pesel:");
        jLabel27.setName("Login"); // NOI18N

        Pesel.setName("Nrkonta"); // NOI18N

        javax.swing.GroupLayout DodajklientaLayout = new javax.swing.GroupLayout(Dodajklienta);
        Dodajklienta.setLayout(DodajklientaLayout);
        DodajklientaLayout.setHorizontalGroup(
            DodajklientaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DodajklientaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DodajklientaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DodajklientaLayout.createSequentialGroup()
                        .addGroup(DodajklientaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DodajklientaLayout.createSequentialGroup()
                                .addGroup(DodajklientaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel22))
                                .addGap(18, 18, 18)
                                .addGroup(DodajklientaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Imie)
                                    .addComponent(Nazwisko)
                                    .addComponent(KAdres1)
                                    .addComponent(KAdres2)))
                            .addGroup(DodajklientaLayout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addGap(30, 30, 30)
                                .addGroup(DodajklientaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(KNrtelefon, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                                    .addComponent(Pesel))))
                        .addGap(199, 199, 199))
                    .addGroup(DodajklientaLayout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(DodajklientaLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(Utwórzklienta)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        DodajklientaLayout.setVerticalGroup(
            DodajklientaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DodajklientaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DodajklientaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(Imie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DodajklientaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(Nazwisko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DodajklientaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(KAdres1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DodajklientaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(KAdres2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DodajklientaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(KNrtelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DodajklientaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(Pesel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(181, 181, 181)
                .addComponent(Utwórzklienta)
                .addContainerGap(230, Short.MAX_VALUE))
        );

        getContentPane().add(Dodajklienta, "Klienci");

        jMenu1.setText("Menu");

        jMenuItem3.setText("Zamówienia");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem1.setText("Zapytanie o produkt");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        Dodaj_klienta.setText("Dodaj klienta");
        Dodaj_klienta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dodaj_klientaActionPerformed(evt);
            }
        });
        jMenu1.add(Dodaj_klienta);

        jMenuItem2.setText("Powrót");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
public class Odbior_synchroniczny  {

    
 public void Odbierzodpowiedz( String selektor) {
        Connection connection = null;
        Session session = null;
        long Czas_odebr_synch = 0;
        long Czas_wyslania_synch = 0;
        ObjectMessage message = null;
        Destination dest = null;
        Zapis_wynikow zapis = new Zapis_wynikow();
        dest = (Destination) reply;

        try {
            connection = connectionFactory.createConnection();
            session = connection.createSession(false, 0);
            String selector = "JMSCorrelationID= '" + selektor + "'";

            MessageConsumer consumer = null;
            consumer = session.createConsumer(dest, selector);

            connection.start();

            Message m = consumer.receive(30000);

            if (m != null) {
Czas_odebr_synch = System.currentTimeMillis();
                if (m instanceof ObjectMessage) {
                    
                    Czas_wyslania_synch = m.getJMSTimestamp();
                    message = (ObjectMessage) m;
                  //  System.out.println(
                   //         "Otrzymano odpowiedz synchronicznie: ");
                    zapis.Zapis(Czas_odebr_synch, m.getJMSTimestamp(), 0, 0, 0,"");
                    //System.out.print("Otrzymano" + licznik);
                }
                //System.out.println(
                //           "Czas wyslania synchronicznie: " + Czas_wyslania_synch);
                //  System.out.println(
                //          "Czas odebrania synch: " + Czas_odebr_synch);
            } else {
                System.out.println("Brak odpowiedzi");
            }

        } catch (JMSException e) {
            System.err.println("Wystąpił wyjątek: " + e.toString());
        } finally {
            if (connection != null) {
                try {
                    connection.close();
                } catch (JMSException e) {
                }
            }
        }
    }

}
    private void list_content(ArrayList<String> col,
            JComboBox list) {
        String s;
        list.removeAllItems();
        Iterator<String> iterator = col.iterator();
        while (iterator.hasNext()) {
            s = iterator.next();
            list.addItem(s);
        }
    }

    public void paintComponent(Graphics g) {
        paintComponent(g);
    }

    void table_content1() {

        Dostawcy.setModel(model1);
        fasada.update_data();

        Object[][] dostawcy = fasada.getproviders();
        model1.setData(dostawcy);
    }

    void table_content2(String numerzamowienia) {
        // Produkty_zamowienie.setModel(model1);
        fasada.update_data();

        model3 = new ProduktyzamowienieTableModel();
        Pozycje.setModel(model3);
        fasada.update_data();
        Object[][] produkty = fasada.getpozycje(numerzamowienia);

        model3.setData(produkty);
    }

    void table_content3() {

        Dostawcy1.setModel(model1);
        fasada.update_data();

        Object[][] dostawcy = fasada.getproviders();
        model1.setData(dostawcy);
    }

    class MyTableModel extends AbstractTableModel {

        private String[] columnNames = {"Nazwa",
            "Producent",
            "Kategoria"
        };
        private Object[][] data;

        public void setData(Object[][] val) {
            data = val;
        }

        public int getColumnCount() {
            return columnNames.length;
        }

        public int getRowCount() {
            return data.length;
        }

        public String getColumnName(int col) {
            return columnNames[col];
        }

        public Object getValueAt(int row, int col) {
            return data[row][col];
        }

        public Class getColumnClass(int c) {
            return getValueAt(0, c).getClass();
        }

        public boolean isCellEditable(int row, int col) {
            if (col < 0) {
                return false;
            } else {
                return true;
            }
        }

        public void setValueAt(Object value, int row, int col) {
            data[row][col] = value;
            fireTableCellUpdated(row, col);
        }
    }

    class DostawcaTableModel extends MyTableModel {

        private String[] columnNames1 = {
            "Nazwa",
            "Adres",
            "NIP"
        };

        public String getColumnName(int col) {
            return columnNames1[col];
        }
    }

    class ProduktyzamowienieTableModel extends DostawcaTableModel {

        private String[] columnNames2 = {
            "Nazwa",
            "Producent",
            "Ilość"
        };

        public String getColumnName(int col) {
            return columnNames2[col];
        }
    }

    void Pokaz_produkty() {
        String dane_1 = model1.getValueAt(row, 2).toString();
        fasada.update_data();

        ArrayList<String> help3 = fasada.getproduktydostawcy(dane_1);
        if (help3 != null) {
            list_content(help3, Lista_produktow);
        }
    }

    void Pokaz_produkty1() {
        String dane_1 = model1.getValueAt(row, 2).toString();
        fasada.update_data();

        ArrayList<String> help3 = fasada.getproduktydostawcy(dane_1);
        if (help3 != null) {
            list_content(help3, produktydostawcy1);
        }
    }

    private class RowListener1 implements ListSelectionListener {

        public void valueChanged(ListSelectionEvent event) {
            if (event.getValueIsAdjusting()) {
                return;
            }
            row = Dostawcy.getSelectionModel().getLeadSelectionIndex();
            Pokaz_produkty();
        }
    }

    private class RowListener2 implements ListSelectionListener {

        public void valueChanged(ListSelectionEvent event) {
            if (event.getValueIsAdjusting()) {
                return;
            }
            row = Dostawcy1.getSelectionModel().getLeadSelectionIndex();
            Pokaz_produkty1();
        }
    }

    private void UtworzdostawceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UtworzdostawceActionPerformed

        String dane_dostawca1[] = {Nazwa.getText(), NIP.getText(), Adres1.getText(), Adres2.getText(), Nrtelefon.getText(), Nrkonta.getText()};

        if (dane_dostawca1[0].equals("") || dane_dostawca1[1].equals("") || dane_dostawca1[2].equals("") || dane_dostawca1[3].equals("") || dane_dostawca1[4].equals("") || dane_dostawca1[5].equals("")) {
            JOptionPane.showMessageDialog(this, "Prosze podać dane");
            return;
        }

        try {
            Integer.parseInt(Nrtelefon.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "W polu 'numer telefonu' wymagany format liczbowy");
            return;
        }

        String wynik = fasada.dodaj_dostawce(dane_dostawca1);
        fasada.dodaj_dostawcow();
        //fasada.update_data();
        if (wynik == null) {
            JOptionPane.showMessageDialog(this, "Ten dostawca już istnieje");
        } else {
            JOptionPane.showMessageDialog(this, "Utworzono dostawce o numerze NIP " + NIP.getText().toString());
        }

        Nazwa.setText("");
        NIP.setText("");
        Adres1.setText("");
        Adres2.setText("");
        Nrtelefon.setText("");
        Nrkonta.setText("");

        // table_content1();  
        // TODO add your handling code here:
    }//GEN-LAST:event_UtworzdostawceActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CardLayout la = (CardLayout) this.getContentPane().getLayout();
        la.show(this.getContentPane(), "Dostawcy");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CardLayout la = (CardLayout) this.getContentPane().getLayout();
        la.show(this.getContentPane(), "Produkty");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ProducentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProducentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProducentActionPerformed

    private void KategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KategoriaActionPerformed

    private void CenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CenaActionPerformed

    private void DostawcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DostawcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DostawcaActionPerformed

    private void Add_produktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_produktActionPerformed
        /*
         String k;
         if (Nazwa_prod.getText().equals("") || Producent.getText().equals("") || Kategoria.getText().equals("") || Cena.getText().equals("") || Dostawca.getText().equals("") || ilosc.getText().equals("")) {
         JOptionPane.showMessageDialog(this, "Prosze podać dane");
         return;
         }
         String data[] = {Nazwa_prod.getText(), Producent.getText(), Kategoria.getText(), Cena.getText()};
         String dost = Dostawca.getText();
         int Ilosc = Integer.parseInt(ilosc.getText());

         try {
         Float.parseFloat(Cena.getText());

         } catch (NumberFormatException e) {
         JOptionPane.showMessageDialog(this, "W polu 'cena' wymagany format liczbowy");
         return;
         }
         try {
         Integer.parseInt(Dostawca.getText());

         } catch (NumberFormatException e) {
         JOptionPane.showMessageDialog(this, "W polu 'Dostawca' wymagany format liczbowy");
         return;
         }

         k = fasada.dodaj_produkt(data, dost, Ilosc);
         if (k == "brak") {
         JOptionPane.showMessageDialog(null, "Dostawca produktu nie istnieje w bazie");
         }

         if (k == null) {
         JOptionPane.showMessageDialog(null, "Produkt o podanych parametrach już istnieje w bazie");
         }
         if (k == "OK") {
         JOptionPane.showMessageDialog(null, "Dodano produkt do bazy");
         }
         */
        for (int i = 0; i < 2500; i++) {
            String data[] = {Integer.toString(i), Integer.toString(i), Integer.toString(i), Integer.toString(i)};
            fasada.dodaj_produkt(data, "1", 1);
            if (i == 101) {
                System.out.print("Dodano produkty");
            }
        }
        fasada.dodaj_produkty();
        Nazwa_prod.setText("");
        Producent.setText("");
        Kategoria.setText("");
        Cena.setText("");
        Dostawca.setText("");
       // table_content();

        // TODO add your handling code here:
    }//GEN-LAST:event_Add_produktActionPerformed

    private void Dodaj_egzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dodaj_egzActionPerformed

        if (!Produkty.getSelectionModel().isSelectionEmpty()) {

            if (Numer_seryjny.getText().equals("") || Data_waznosci_D.getText().equals("") || Data_produkcji_D.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Prosze podać dane");
                return;
            }
            try {
                Integer.parseInt(Numer_seryjny.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Wymagany format liczbowy");
                return;
            }

            /*      
             String nazwa =(String) model.getValueAt(row, 0);
             String producent = (String) model.getValueAt(row, 1);
             String data2[] = {nazwa,producent,Numer_seryjny.getText(),Data_produkcji_D.getText(),Data_produkcji_M.getText(),Data_produkcji_Y.getText(),Data_waznosci_D.getText(),Data_waznosci_M.getText(),Data_waznosci_Y.getText()};
             String dane_1 [] = {(String) model.getValueAt(row, 0),(String) model.getValueAt(row, 1)};
             */
            //    fasada.dodaj_egzemplarzproduktu(data2);
            //tbase.update_data();
            //     ArrayList<String> help3 = fasada.getegzemplarze(dane_1);
            //    if (help3 != null) {
            //      list_content(help3, Egzemplarze);
            //   }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_Dodaj_egzActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        CardLayout la = (CardLayout) this.getContentPane().getLayout();
        la.show(this.getContentPane(), "Zamowienia");
        table_content1();

        //  Pokaz_produkty();
        //     ArrayList<String> help3 =  fasada.getdostawcy2();
        //   if (help3 != null) {
        //         list_content(help3, Dostawcy);
        //   }
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        fasada.update_data();
        /*
         String nr_zam1 = numerzam.getText().toString();
         String ilosc = Ilosc.getText().toString();
         String dost1 = model1.getValueAt(row, 2).toString();
         int wybranyprodukt = Lista_produktow.getSelectedIndex();
         */
        for (int i = 0; i < 100; i++) {
            String numer = Integer.toString(i);
            fasada.dodaj_pozycje_zamowienia(0, "1", numer, "1");
        }
        fasada.dodaj_pozycje_zamowien();
        /*
         fasada.dodaj_pozycje_zamowienia(wybranyprodukt, dost1, nr_zam1, ilosc);

        
         table_content2(nr_zam1);
         */

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void Wyslij_zamowienieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Wyslij_zamowienieActionPerformed
     Odbior_synchroniczny odbior = new Odbior_synchroniczny();   
        fasada.update_data();
        
        messagebean.update_data();
        for (int i = 0; i < 100; i++) {
            String numer = Integer.toString(i);
            String Selektor = messagebean.Wyslijzamowienie(numer);
         //   System.out.print(i);
odbior.Odbierzodpowiedz(Selektor);
//System.out.print(licznik);
//licznik= licznik+1;
     
           try {
           Thread.sleep(5000);

       } catch (InterruptedException ex) {
              Logger.getLogger(Client_Sklep.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
       // String numer = numerzam.getText();

        // TODO add your handling code here:
    }//GEN-LAST:event_Wyslij_zamowienieActionPerformed

   


    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        /*
         String numer = numerzam.getText().toString();
         String danedostawcy = model1.getValueAt(row, 2).toString();
         fasada.update_data();

         String wynik = fasada.dodaj_zamowienie1(danedostawcy, numer);

         if ("Juz jest".equals(wynik)) {
         System.out.println("Zamowienie o tym numerze juz istnieje");
         } else {
         fasada.dodaj_zamowienia();
         table_content2(numer);
         }
        
         */
        for (int i = 0; i < 100; i++) {
            String numer = Integer.toString(i);
            String danedostawcy = "1";
            fasada.update_data();
            String wynik = fasada.dodaj_zamowienie1(danedostawcy, numer);
            fasada.dodaj_zamowienia();

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        CardLayout la = (CardLayout) this.getContentPane().getLayout();
        la.show(this.getContentPane(), "Zapytanie");
        table_content3();        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        messagebean.test();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        CardLayout la = (CardLayout) this.getContentPane().getLayout();
        la.show(this.getContentPane(), "Pusty");    // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        System.out.println(System.currentTimeMillis());        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void Dodaj_klientaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dodaj_klientaActionPerformed
        CardLayout la = (CardLayout) this.getContentPane().getLayout();
        la.show(this.getContentPane(), "Klienci");        // TODO add your handling code here:
    }//GEN-LAST:event_Dodaj_klientaActionPerformed

    private void UtwórzklientaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UtwórzklientaActionPerformed

        String dane_klient[] = {Imie.getText(), Nazwisko.getText(), KAdres1.getText(), KAdres2.getText(), KNrtelefon.getText(), Pesel.getText()};

        if (dane_klient[0].equals("") || dane_klient[1].equals("") || dane_klient[2].equals("") || dane_klient[3].equals("") || dane_klient[4].equals("") || dane_klient[5].equals("")) {
            JOptionPane.showMessageDialog(this, "Prosze podać dane");
            return;
        }

        try {
            Integer.parseInt(KNrtelefon.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "W polu 'numer telefonu' wymagany format liczbowy");
            return;
        }

        String wynik = fasada.dodaj_klienta(dane_klient);
        fasada.dodaj_klientow();
        //fasada.update_data();
        if (wynik == null) {
            JOptionPane.showMessageDialog(this, "Ten klient już istnieje");
        } else {
            JOptionPane.showMessageDialog(this, "Utworzono klienta o numerze Pesel " + Pesel.getText().toString());
        }

        Imie.setText("");
        Nazwisko.setText("");
        KAdres1.setText("");
        KAdres2.setText("");
        KNrtelefon.setText("");
        Pesel.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_UtwórzklientaActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        fasada.update_data();

        String nr_zam1 = numerzam.getText().toString();
        String ilosc = "1";
        String dost1 = "1";
        int wybranyprodukt = Lista_produktow.getSelectedIndex();
        for (int j = 0; j < 100; j++) {
            String numer = Integer.toString(j);
            for (int i = 0; i < 2250; i++) {

                fasada.dodaj_pozycje_zamowienia(i, "1", numer, "1");

            }
            fasada.dodaj_pozycje_zamowien();
        }

        // table_content2(nr_zam1);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void Wyślij_zapytanieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Wyślij_zapytanieActionPerformed
        messagebean.update_data();
        String danedostawcy = model1.getValueAt(row, 2).toString();
        String tresc = tresc_zapytania.getText();
        int wybrany = produktydostawcy1.getSelectedIndex();
        messagebean.Zapytanieoprodukt(wybrany, danedostawcy, tresc);           // TODO add your handling code here:
    }//GEN-LAST:event_Wyślij_zapytanieActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client_Sklep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client_Sklep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client_Sklep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client_Sklep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Client_Sklep().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_produkt;
    private javax.swing.JTextField Adres1;
    private javax.swing.JTextField Adres2;
    private javax.swing.JTextField Cena;
    private javax.swing.JTextField Data_produkcji_D;
    private javax.swing.JTextField Data_produkcji_M;
    private javax.swing.JTextField Data_produkcji_Y;
    private javax.swing.JTextField Data_waznosci_D;
    private javax.swing.JTextField Data_waznosci_M;
    private javax.swing.JTextField Data_waznosci_Y;
    private javax.swing.JPanel Dodaj_dostawce;
    private javax.swing.JButton Dodaj_egz;
    private javax.swing.JPanel Dodaj_egzemplarz;
    private javax.swing.JMenuItem Dodaj_klienta;
    private javax.swing.JPanel Dodaj_produkt;
    private javax.swing.JPanel Dodaj_zamowienie;
    private javax.swing.JPanel Dodajklienta;
    private javax.swing.JTextField Dostawca;
    private javax.swing.JTable Dostawcy;
    private javax.swing.JTable Dostawcy1;
    private javax.swing.JComboBox Egzemplarze;
    private javax.swing.JTextField Ilosc;
    private javax.swing.JTextField Imie;
    private javax.swing.JTextField KAdres1;
    private javax.swing.JTextField KAdres2;
    private javax.swing.JTextField KNrtelefon;
    private javax.swing.JTextField Kategoria;
    private javax.swing.JComboBox Lista_produktow;
    private javax.swing.JTextField NIP;
    private javax.swing.JTextField Nazwa;
    private javax.swing.JTextField Nazwa_prod;
    private javax.swing.JTextField Nazwisko;
    private javax.swing.JTextField Nrkonta;
    private javax.swing.JTextField Nrtelefon;
    private javax.swing.JTextField Numer_seryjny;
    private javax.swing.JTextField Pesel;
    private javax.swing.JTable Pozycje;
    private javax.swing.JTextField Producent;
    private javax.swing.JTable Produkty;
    private javax.swing.JPanel Pusty;
    private javax.swing.JButton Utworzdostawce;
    private javax.swing.JButton Utwórzklienta;
    private javax.swing.JButton Wyslij_zamowienie;
    private javax.swing.JButton Wyślij_zapytanie;
    private javax.swing.JPanel Zapytanieoprodukt;
    private javax.swing.JTextField ilosc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField numerzam;
    private javax.swing.JComboBox produktydostawcy1;
    private javax.swing.JTextField tresc_zapytania;
    // End of variables declaration//GEN-END:variables
}
